# Generated by Django 4.2.20 on 2025-03-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_paciente', models.CharField(max_length=50, unique=True)),
                ('numero_centro', models.CharField(max_length=50)),
                ('numero_pesquisador', models.CharField(max_length=50)),
                ('data_observacao', models.DateField()),
                ('fase_tratamento', models.CharField(choices=[('fase1', 'Fase 1 - Início do tratamento'), ('fase1b', 'Fase 1B - Menos de 3 meses de tratamento'), ('fase2', 'Fase 2 - 3 a 6 meses de tratamento'), ('fase3', 'Fase 3 - Mais de 6 meses de tratamento')], max_length=10)),
            ],
        ),
    ]
