# Generated by Django 4.2.20 on 2025-03-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_paciente_fase_tratamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxoReducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta_atual', models.IntegerField()),
                ('resposta', models.CharField(blank=True, max_length=50, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.paciente')),
            ],
        ),
    ]
