# Generated by Django 4.2.20 on 2025-03-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fluxoreducao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FluxoReducao',
            new_name='FluxoRedu',
        ),
    ]
