# Generated by Django 4.2.20 on 2025-03-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_resposta_delete_fluxoredu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
