# Generated by Django 4.2.20 on 2025-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_alter_resposta_resposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MTX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pergunta', models.IntegerField(default=1)),
                ('texto', models.CharField(max_length=255)),
                ('fase_tratamento', models.CharField(choices=[('fase1', 'Fase 1 - Início do tratamento'), ('fase1b', 'Fase 1B - Menos de 3 meses de tratamento'), ('fase2', 'Fase 2 - 3 a 6 meses de tratamento'), ('fase3', 'Fase 3 - Mais de 6 meses de tratamento'), ('reducao', 'Redução')], max_length=10)),
            ],
            options={
                'unique_together': {('numero_pergunta', 'fase_tratamento')},
            },
        ),
    ]
