# Generated by Django 4.2.20 on 2025-04-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_mtx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MTX',
        ),
    ]
