# Generated by Django 4.2.20 on 2025-04-16 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0013_delete_mtx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='pergunta_anterior',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='desvio_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desvio', to='galeria.pergunta'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='proxima_se_nao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxima_nao', to='galeria.pergunta'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='proxima_se_sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxima_sim', to='galeria.pergunta'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='retornar_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retorno', to='galeria.pergunta'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fase_tratamento',
            field=models.CharField(choices=[('fase1', 'Fase 1 - Início do tratamento'), ('fase1b', 'Fase 1B - Menos de 3 meses de tratamento'), ('fase2', 'Fase 2 - 3 a 6 meses de tratamento'), ('fase3', 'Fase 3 - Mais de 6 meses de tratamento'), ('reducao', 'Redução'), ('mtx', 'MTX'), ('ssz', 'SSZ'), ('lef', 'LEF')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='fase_tratamento',
            field=models.CharField(choices=[('fase1', 'Fase 1 - Início do tratamento'), ('fase1b', 'Fase 1B - Menos de 3 meses de tratamento'), ('fase2', 'Fase 2 - 3 a 6 meses de tratamento'), ('fase3', 'Fase 3 - Mais de 6 meses de tratamento'), ('reducao', 'Redução'), ('mtx', 'MTX'), ('ssz', 'SSZ'), ('lef', 'LEF')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='numero_pergunta',
            field=models.IntegerField(),
        ),
    ]
