# Generated by Django 4.2.20 on 2025-04-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0014_remove_pergunta_pergunta_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='critica_nao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='critica_sim',
            field=models.TextField(blank=True, null=True),
        ),
    ]
