# Generated by Django 4.2.20 on 2025-04-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0015_pergunta_critica_nao_pergunta_critica_sim'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('sim_nao', 'Sim/Não'), ('multipla_escolha', 'Múltipla Escolha')], default='sim_nao', max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fase_tratamento',
            field=models.CharField(choices=[('fase1', 'Fase 1 - Início do tratamento'), ('fase1b', 'Fase 1B - Menos de 3 meses de tratamento'), ('fase2', 'Fase 2 - 3 a 6 meses de tratamento'), ('fase3', 'Fase 3 - Mais de 6 meses de tratamento'), ('reducao', 'Redução'), ('desvio_mtx', 'Desvio - MTX'), ('desvio_ssz', 'Desvio - SSZ'), ('desvio_lef', 'Desvio - LEF'), ('desvio_hcq', 'Desvio - HCQ'), ('desvio_gcs', 'Desvio - Corticoide'), ('desvio_aine', 'Desvio - AINE'), ('desvio_bmmcd', 'Desvio - bMMCD'), ('desvio_aemmcd', 'Desvio - aeMMCD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='fase_tratamento',
            field=models.CharField(choices=[('fase1', 'Fase 1 - Início do tratamento'), ('fase1b', 'Fase 1B - Menos de 3 meses de tratamento'), ('fase2', 'Fase 2 - 3 a 6 meses de tratamento'), ('fase3', 'Fase 3 - Mais de 6 meses de tratamento'), ('reducao', 'Redução'), ('desvio_mtx', 'Desvio - MTX'), ('desvio_ssz', 'Desvio - SSZ'), ('desvio_lef', 'Desvio - LEF'), ('desvio_hcq', 'Desvio - HCQ'), ('desvio_gcs', 'Desvio - Corticoide'), ('desvio_aine', 'Desvio - AINE'), ('desvio_bmmcd', 'Desvio - bMMCD'), ('desvio_aemmcd', 'Desvio - aeMMCD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.CharField(max_length=50),
        ),
    ]
