# Generated by Django 4.2.20 on 2025-04-30 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0016_pergunta_tipo_alter_paciente_fase_tratamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fase_tratamento',
            field=models.CharField(choices=[('fase1', 'Fase 1 - Início do tratamento'), ('fase1b', 'Fase 1B - Menos de 3 meses de tratamento'), ('fase2', 'Fase 2 - 3 a 6 meses de tratamento'), ('fase3', 'Fase 3 - Mais de 6 meses de tratamento'), ('reducao', 'Redução'), ('mtx', 'MTX'), ('ssz', 'SSZ'), ('lef', 'LEF'), ('hcq', 'HCQ'), ('aine', 'AINE'), ('gcs', 'GCS'), ('rostro', 'ROSTRO'), ('aemmcd', 'aeMMCD'), ('bmmcd', 'bMMCD'), ('fase1b', 'Fase 1B')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='fase_tratamento',
            field=models.CharField(choices=[('fase1', 'Fase 1 - Início do tratamento'), ('fase1b', 'Fase 1B - Menos de 3 meses de tratamento'), ('fase2', 'Fase 2 - 3 a 6 meses de tratamento'), ('fase3', 'Fase 3 - Mais de 6 meses de tratamento'), ('reducao', 'Redução'), ('mtx', 'MTX'), ('ssz', 'SSZ'), ('lef', 'LEF'), ('hcq', 'HCQ'), ('aine', 'AINE'), ('gcs', 'GCS'), ('rostro', 'ROSTRO'), ('aemmcd', 'aeMMCD'), ('bmmcd', 'bMMCD'), ('fase1b', 'Fase 1B')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='galeria.pergunta')),
            ],
        ),
    ]
