# Generated by Django 4.2.20 on 2025-05-04 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0018_alter_paciente_fase_tratamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='retornar_para_se_nao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retornar_nao', to='galeria.pergunta'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='retornar_para_se_sim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retornar_sim', to='galeria.pergunta'),
        ),
    ]
