# Generated by Django 4.2.20 on 2025-05-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0019_pergunta_retornar_para_se_nao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='retornar_para_se_nao',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='retornar_para_se_sim',
        ),
    ]
