# Generated by Django 4.2.20 on 2025-07-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0020_remove_pergunta_retornar_para_se_nao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero_paciente',
            field=models.CharField(max_length=50),
        ),
    ]
