# Generated by Django 4.2.20 on 2025-08-21 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0021_alter_paciente_numero_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativa',
            name='proxima_pergunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternativa_proxima', to='galeria.pergunta'),
        ),
    ]
